### ISSUE TITLE
Parser cannot handle multi-line DNS responses

### ISSUE THREAD

**Issue by Qqwy** [trailofbits/dkim-query#8]
Some DNSes return a long record (because e.g. the domain name is long) as multiple lines that are wrapped with `"`.

An example:

Looking up the `google` domainkey for `protodave.com` returns the following result:
```
"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhArxYH88+A76Gk7/8ENefN5RhMFhoYJp8T3KLPYYpejDI45PKWTO+2r8ZJZOtuk7tsG07bmJyU8PFvU48Lf1xtb4WcFxKKjd7N5MF6JcHD51Xb8XDAJA2ldqxH4hBbw9dRjsT7WBFXbp2x6MSWxgi9f1w+7Z2IFG+AtUjrf8/9N3gLieaZKZT1SEhR8TnhfOm" "FG0LfMyS0YtfHKrkUkBCEmWBPisB2CcZBShKr6/T8/UB/oZF8XMRd0NOsru9MGx9Yp89jIYS5YRuvbA0/TLgOOiqrSU5Ms1egMwfFyy4BMDUKayZzF6BxNPc/+UoFrYHKRZpyD/kEd4FXNEddlksQIDAQAB"
```

This library will not be able to parse this header properly because it will stumble on the `" "` in the middle.

**Comment by postmodern** [comment]
dkim-query has been able to handle [multi-string records](https://github.com/trailofbits/dkim-query/commit/cbe8b6872f81d69c2e6635a697a64c71a1df0824#diff-fa9878a279149459ff605535046d43ccR34) for a while.

    > DKIM::Query::Domain.query('protodave.com')
    => #<DKIM::Query::Domain:0x000056182ea4d6b0 @name="protodave.com", @keys={"google"=>#<DKIM::Query::Key:0x000056182ea4d750 @v=:DKIM1, @g=nil, @h=nil, @k=:rsa, @n=nil, @p="MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhArxYH88+A76Gk7/8ENefN5RhMFhoYJp8T3KLPYYpejDI45PKWTO+2r8ZJZOtuk7tsG07bmJyU8PFvU48Lf1xtb4WcFxKKjd7N5MF6JcHD51Xb8XDAJA2ldqxH4hBbw9dRjsT7WBFXbp2x6MSWxgi9f1w+7Z2IFG+AtUjrf8/9N3gLieaZKZT1SEhR8TnhfOmFG0LfMyS0YtfHKrkUkBCEmWBPisB2CcZBShKr6/T8/UB/oZF8XMRd0NOsru9MGx9Yp89jIYS5YRuvbA0/TLgOOiqrSU5Ms1egMwfFyy4BMDUKayZzF6BxNPc/+UoFrYHKRZpyD/kEd4FXNEddlksQIDAQAB"@18, @s=nil, @t=nil>}>
